services:
  knowledgeBase:
    image: neo4j:latest
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/ostisGovno
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - /home/meteorych/neo4j/data:/data
      - /home/meteorych/neo4j/data:/import

  redisBroker:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379


    

