#Author: Vodohleb04
"""
    Commands for work with CRUDAgent
"""
from .categories_of_region_command import CategoriesOfRegionCommand
from .landmarks_by_coordinates_command import LandmarksByCoordinatesCommand
from .landmarks_by_names_command import LandmarksByNamesCommand
from .landmarks_by_region_command import LandmarksByRegionCommand
from .landmarks_in_map_sectors_command import LandmarksInMapSectorsCommand
from .landmarks_of_categories_in_region_command import LandmarksOfCategoriesInRegionCommand
from .landmarks_refers_to_categories_command import LandmarksRefersToCategoriesCommand
from .recommendations_for_landmark_by_region_command import RecommendationsForLandmarkByRegionCommand
from .map_sectors_of_points_command import MapSectorsOfPointsCommand
from .landmarks_of_categories_in_map_sectors_command import LandmarksOfCategoriesInMapSectorsCommand
