import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TheHeader } from '@/components/TheHeader'
import { TheFooter } from '@/components/TheFooter'
import './../node_modules/leaflet/dist/leaflet.css'
import 'leaflet/dist/leaflet'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TRAVELER.AI',
  description: 'Generated by group of hungry students',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        {children}
        {/*<TheFooter />*/}
      </body>
    </html>
  )
}
